DROP TABLE IF EXISTS "uses" CASCADE;
DROP TABLE IF EXISTS "cleaninglog" CASCADE;
DROP TABLE IF EXISTS "roomcheck" CASCADE;
DROP TABLE IF EXISTS "belongsto" CASCADE;
DROP TABLE IF EXISTS "housekeepingtask" CASCADE;
DROP TABLE IF EXISTS "cleaningsupplies" CASCADE;
DROP TABLE IF EXISTS "housekeepingemployee" CASCADE;
DROP TABLE IF EXISTS "housekeepingstatus" CASCADE;
DROP TABLE IF EXISTS "tasktype" CASCADE;
DROP TABLE IF EXISTS "room" CASCADE;

